### ISSUE TITLE
Dataframes not the same length

### ISSUE THREAD

**Issue by finsellwood** [finsellwood/DeepMODE#4]
df_1 and df_2 are apparently incompatible lengths, despite coming from the same original dataframe.

**Comment by adambrzosko** [comment]
Have a look at a way to load the data from root that does not involve data frames

**Comment by finsellwood** [comment]
Could be because the lists of objects are unpacked into consecutive rows, causing a blank (bar one element) row which isn't included(?)

**Comment by adambrzosko** [comment]
Changed the loading method from uproot to root_numpy - the lengths look fine, plus all the variables including clusters load properly!
